apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-controller
          image: nginx