apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp-deployment
  namespace: default
  labels:
    app:  myapp-dep
    type: fornt-end
spec:
  selector:
    matchLabels:
      app: myapp-prod-deploy
      type: fornt-end
  replicas: 1
  #strategy:
    #rollingUpdate:
      #maxSurge: 25%
      #maxUnavailable: 25%
    #type: RollingUpdate
  template:
    metadata:
      labels:
        app:  myapp-prod-deploy
        type: fornt-end
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx-containers-deploy
        image:  nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always