apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ipam-db-deployment
  namespace: default
  labels:
    app:  ipam-db
spec:
  selector:
    matchLabels:
      app: ipam-db
  replicas: 3
  template:
    metadata:
      labels:
        app:  ipam-db
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  database
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: nazmul
        #ports:
          #- containerPort: 3306
            #name: mysql
