apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service 
spec:
  selector:
    app: demo-votting-app
    name: redis-pod
  ports:
  - port: 6379
    targetPort: 6379
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.