apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: demo-votting-app
    name: result-service
spec:
  selector:
    app: demo-votting-app
    name: result-app-pod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005