apiVersion: v1
kind: Service
metadata:
  name: voting
  labels:
    app: demo-votting-app
    name: votting-service
spec:
  selector:
    app: demo-votting-app
    name: votting-app-pod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004