apiVersion: v1
kind: Pod
metadata:
  name: votting-app-pod
  labels:
    app: demo-votting-app
    name: votting-app-pod
spec:
  containers:
  - name: votting-app
    image: kodekloud/examplevotingapp_vote:v1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
    ports:
    - containerPort:  80
