apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: demo-votting-app
    name: worker-pod
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi