apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    type: test-deployment
    name: myapp
spec:
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      name: myapp-pod
      labels:
        color: blue
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7.10-nazmul
  replicas: 5