apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: web
    type: front-end

spec:
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      name: myapp
      labels:
        color: blue
    spec:
      containers:
        - name: myapp-container
          image: nginx
  replicas: 2