apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ipam-web-deployment
  namespace: default
  labels:
    app:  ipam-web
spec:
  selector:
    matchLabels:
      app: ipam-web
  replicas: 3
  template:
    metadata:
      labels:
        app:  ipam-web
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: fornt-end
        image: pierrecdn/phpipam
        env:
        - name: MYSQL_ENV_MYSQL_ROOT_PASSWORD
          value: nazmul