apiVersion: v1
kind: Service
metadata:
  name: ipam-db-service
  namespace: default
spec:
  selector:
    app: ipam-db
  type: NodePort
  ports:
  - name: ipam-db-port
    protocol: TCP
    port: 3306
    targetPort: 3306
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30013