apiVersion: v1
kind: Pod
metadata:
  name: test-web
  labels:
    app: my-app2
    devlop: fornt-end
    user: sre
spec:
  containers:
  - name: nginx-web-server
    image: nginx
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP