apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ipam-web
  labels:
    app: ipam-kube
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:     
      - name: pam
        image: pierrecdn/phpipam
        env:
        - name: MYSQL_ENV_MYSQL_ROOT_PASSWORD
          value: nazmul