apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ipam-db
  labels:
    app: ipam-kube
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
      - name: db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: nazmul
        #ports:
          #- containerPort: 3306
            #name: mysql